CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    user_name VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    last_active TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS roles (
    id INT AUTO_INCREMENT PRIMARY KEY,
    role VARCHAR(50) UNIQUE NOT NULL
);

INSERT IGNORE INTO roles (role) VALUES ('admin'), ('user');

CREATE TABLE IF NOT EXISTS user_roles (
    user_id INT,
    role VARCHAR(50),
    PRIMARY KEY (role, user_id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (role) REFERENCES roles(role) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS tasks (
    task_id VARCHAR(100) PRIMARY KEY UNIQUE NOT NULL,
    user_id INT NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    category VARCHAR(100),
    status ENUM('pending', 'running', 'completed') DEFAULT 'pending',
    creation_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    duration INT DEFAULT 0,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
)